### ISSUE TITLE
New 403 Forbidden and questions.

### ISSUE THREAD

**Issue by gilles33377** [danpla/pindl#3]
Hi : Here a new 403 Forbidden. Here the debug : 
DEBUG: 1 new pins on this page
 399/5702                                                    674977062872466575
ERROR: HTTP Error 403: Forbidden

Some questions : 
Why when we start downloading some pins we start at less than 100 (example in screenshot ?)
Can you make a -all option for others people or it is restricted by the API ?
How to add request or ideas to add functions for your script ?
At last : Thanks for your work ;)

![1236](https://user-images.githubusercontent.com/27515067/27455248-fa0be352-579c-11e7-99b6-7ec74cbc989b.jpg)

**Comment by danpla** [comment]
The problem with https://www.pinterest.com/pin/674977062872466575/ is the same as in #2, except the image is in the WEBP format. I'll add a workaround soon.

> Why when we start downloading some pins we start at less than 100

This is described in the README: [Rate limiting and pagination](https://github.com/danpla/pindl#rate-limiting-and-pagination). The whole point is to not make API calls for already downloaded pages, thus saving the number of available requests per second.

> How to add request or ideas to add functions for your script ?

Simply create a new issue for each one.

> Thanks for your work ;)

You're welcome!

**Comment by gilles33377** [comment]
Thanks ;)

**Comment by gilles33377** [comment]
Last question : Can you make a -all option for others people or it is restricted by the API ?

**Comment by danpla** [comment]
This is the API's restriction.

**Comment by danpla** [comment]
Oh, wait: you mean to add functionality to download all boards of another users?

**Comment by gilles33377** [comment]
Yes.

**Comment by danpla** [comment]
Yes, the API doesn't provide such information. The only available info is listed here: https://developers.pinterest.com/docs/api/users/#user-object

As an alternative, you can save URLs of the boards you want to download in a textual file, one URL per line, and the feed it to pindl with `-b` argument:

    pindl.py -b your_file.txt
