### ISSUE TITLE
Is there a way to get the pin.link from the API?

### ISSUE THREAD

**Issue by HughP** [danpla/pindl#6]
in the API docs the say it is the link attribute of the the pin.
https://developers.pinterest.com/docs/api/pins/?

"The URL of the webpage where the Pin was created."

**Comment by danpla** [comment]
Are you trying to use pindl as a Python module? It's not designed for this: it only queries the minimal set of API fields (id, note, and image) needed to implement the functionality. Maybe there is a full-featured Python module for interacting with Pinterest somewhere on the Internet, but be aware that "link" filed usually refers to 404 pages.
